"""initial_schema

Revision ID: b69018dd58bc
Revises: 
Create Date: 2026-01-29 06:11:44.198243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69018dd58bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email, must be unique'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Display name, must be unique'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hash, never return in API'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Admin role for verification permissions'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Account creation timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Owner of the contribution'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Contribution title, max 200 chars'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of contribution'),
    sa.Column('type', sa.Enum('IDEA', 'WORK', 'ASSET', name='contribution_type_enum'), nullable=False, comment='Category: idea, work or asset'),
    sa.Column('file_url', sa.String(length=500), nullable=True, comment='Optional external file URL (HTTPS only, validate in Pydantic)'),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'NEEDS_CHANGES', name='contribution_status_enum'), nullable=False, comment='Current state in verification workflow'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Submission timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_status'), ['status'], unique=False)
        batch_op.create_index('ix_contributions_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_user_id'), ['user_id'], unique=False)

    op.create_table('verification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False, comment='Contribution being verified'),
    sa.Column('admin_id', sa.Integer(), nullable=False, comment='Admin who made the decision'),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'REQUEST_CHANGES', name='verification_decision_enum'), nullable=False, comment='Admin decision: APPROVE, REJECT, or REQUEST_CHANGES'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional feedback from admin'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When decision was made (UTC)'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_logs_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_logs_contribution_id'), ['contribution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_verification_logs_id'))
        batch_op.drop_index(batch_op.f('ix_verification_logs_contribution_id'))
        batch_op.drop_index(batch_op.f('ix_verification_logs_admin_id'))

    op.drop_table('verification_logs')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_user_id'))
        batch_op.drop_index('ix_contributions_status_created_at')
        batch_op.drop_index(batch_op.f('ix_contributions_status'))
        batch_op.drop_index(batch_op.f('ix_contributions_id'))
        batch_op.drop_index(batch_op.f('ix_contributions_created_at'))

    op.drop_table('contributions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
